"""Assemble a private LTspice workspace using the owner's existing models.

Python standard library only. Never downloads or publishes third-party files.
Destination must not already exist, to protect edited scenarios and results.
"""
from pathlib import Path
import argparse
import shutil
import re


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--models', type=Path, required=True,
                        help='Original project directory containing models, symbols and LG_single.asc')
    parser.add_argument('--ltspice-lib', type=Path, required=True,
                        help='Installed LTspice lib directory containing cmp, sym and sub')
    parser.add_argument('--destination', type=Path, required=True,
                        help='New private workspace outside this repository')
    args = parser.parse_args()
    repo = Path(__file__).resolve().parents[1]
    dest = args.destination.resolve()
    if dest == repo or repo in dest.parents:
        parser.error('Use a destination outside the repository to avoid publishing models.')
    if dest.exists():
        parser.error('Destination already exists; choose a new directory.')
    copies = [(p, Path(p.name)) for p in (repo / 'simulation/ltspice').iterdir()
              if p.suffix in {'.asc', '.cir', '.net', '.bias'}]
    required = ['AO3401A.mod', 'CA3096.lib', 'LM311.sub', 'TL431.sub',
                'darlngtn.lib', 'irf7328.spi', 'nat_semi.lib', 'opamp.lib',
                'phil_bjt.lib', 'phil_fet.lib', 'pwrbjt.lib', 'scr.txt',
                'AO3401A.asy', 'TL431.asy', 'LG_single.asy', 'LG_single.asc']
    copies += [(p, Path(p.name)) for p in (repo / 'simulation/launchers').iterdir() if p.is_file()]
    copies += [(args.models / name, Path(name)) for name in required]
    copies += [(args.ltspice_lib / 'cmp' / name, Path(name))
               for name in ['standard.bjt', 'standard.dio', 'standard.jft', 'standard.mos']]
    copies += [(args.ltspice_lib / 'sub/LTC1044.sub', Path('LTC1044.sub'))]
    copies += [(args.ltspice_lib / 'sym' / name, Path(name))
               for name in ['AutoGenerated/2N7000_PLP.asy', 'PowerProducts/LTC1044.asy']]
    missing = [str(src) for src, _ in copies if not src.is_file()]
    if missing:
        parser.error('Missing dependencies:\n' + '\n'.join(missing))
    dest.mkdir(parents=True)
    for src, relative in copies:
        target = dest / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, target)
    symbol = dest / 'AutoGenerated/2N7000_PLP.asy'
    content = symbol.read_bytes().decode('cp1252')
    content = re.sub(r'SYMATTR ModelFile [^\r\n]+',
                     'SYMATTR ModelFile phil_fet.lib', content)
    symbol.write_bytes(content.encode('cp1252'))
    print(f'Prepared {dest}. Models are private local copies, not redistributed.')
    print('Simulation completion and numerical comparison must be checked separately.')


if __name__ == '__main__':
    main()
