param([string]$Models, [string]$LtspiceLib, [string]$Destination, [switch]$NoOpen)
$ErrorActionPreference = 'Stop'
try {
    $repo = Split-Path $PSScriptRoot -Parent
    if (!$Models) {
        Add-Type -AssemblyName System.Windows.Forms
        $picker = New-Object System.Windows.Forms.FolderBrowserDialog
        $picker.Description = 'Seleccionar la carpeta que contiene los modelos del proyecto y LG_single.asc'
        if ($picker.ShowDialog() -ne 'OK') { throw 'Preparacion cancelada; no se copiaron archivos.' }
        $Models = $picker.SelectedPath
    }
    if (!$LtspiceLib) { $LtspiceLib = Join-Path $env:LOCALAPPDATA 'LTspice\lib' }
    if (!$Destination) { $Destination = Join-Path $repo 'LTspice-local' }
    $Destination = [IO.Path]::GetFullPath($Destination)
    if (Test-Path -LiteralPath $Destination) { throw 'La carpeta de destino ya existe. Conservela o elija otra con -Destination.' }
    $copies = @()
    foreach ($file in Get-ChildItem -LiteralPath "$repo\simulation\ltspice" -File) {
        if ($file.Extension -in '.asc','.cir','.net','.bias','.plt') {
            $copies += @{Source=$file.FullName; Target=$file.Name}
        }
    }
    foreach ($file in Get-ChildItem -LiteralPath "$repo\simulation\launchers" -File) {
        $copies += @{Source=$file.FullName; Target=$file.Name}
    }
    $required = 'AO3401A.mod','CA3096.lib','LM311.sub','TL431.sub','darlngtn.lib','irf7328.spi','nat_semi.lib','opamp.lib','phil_bjt.lib','phil_fet.lib','pwrbjt.lib','scr.txt','AO3401A.asy','TL431.asy','LG_single.asy','LG_single.asc'
    foreach ($name in $required) { $copies += @{Source=(Join-Path $Models $name); Target=$name} }
    $installed = @{
        'cmp\standard.bjt'='standard.bjt'; 'cmp\standard.dio'='standard.dio'
        'cmp\standard.jft'='standard.jft'; 'cmp\standard.mos'='standard.mos'
        'sub\LTC1044.sub'='LTC1044.sub'
        'sym\AutoGenerated\2N7000_PLP.asy'='AutoGenerated\2N7000_PLP.asy'
        'sym\PowerProducts\LTC1044.asy'='PowerProducts\LTC1044.asy'
    }
    foreach ($item in $installed.GetEnumerator()) {
        # A previously prepared folder can supply the dependencies as well.
        $source = Join-Path $Models $item.Value
        if (!(Test-Path -LiteralPath $source -PathType Leaf)) { $source = Join-Path $LtspiceLib $item.Key }
        $copies += @{Source=$source; Target=$item.Value}
    }
    $missing = @($copies | Where-Object { !(Test-Path -LiteralPath $_.Source -PathType Leaf) })
    if ($missing.Count) { throw ("Faltan dependencias:`n" + (($missing | ForEach-Object {$_.Source}) -join "`n")) }
    New-Item -ItemType Directory -Path $Destination | Out-Null
    foreach ($copy in $copies) {
        $target = Join-Path $Destination $copy.Target
        New-Item -ItemType Directory -Force -Path (Split-Path $target -Parent) | Out-Null
        Copy-Item -LiteralPath $copy.Source -Destination $target
    }
    $symbol = Join-Path $Destination 'AutoGenerated\2N7000_PLP.asy'
    $encoding = [Text.Encoding]::GetEncoding(1252)
    $content = [IO.File]::ReadAllText($symbol, $encoding)
    $content = $content -replace 'SYMATTR ModelFile [^\r\n]+', 'SYMATTR ModelFile phil_fet.lib'
    [IO.File]::WriteAllText($symbol, $content, $encoding)
    $hashes = Get-ChildItem -LiteralPath $Destination -Recurse -File | ForEach-Object {
        @{file=$_.FullName.Substring($Destination.TrimEnd('\').Length+1); sha256=(Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash}
    }
    $hashes | ConvertTo-Json -Depth 3 | Set-Content -LiteralPath (Join-Path $Destination 'prepared-files.json') -Encoding UTF8
    Write-Host "Listo: $Destination"
    Write-Host 'SIM-09: abrir SIM-09_loop_5V.asc o SIM-09_loop_33V.asc y Run (solver Alternate).'
    Write-Host 'Tambien puede usar PROBAR_SIM09_5V.cmd o PROBAR_SIM09_33V.cmd.'
    if (!$NoOpen) { Invoke-Item -LiteralPath $Destination }
} catch { Write-Host $_ -ForegroundColor Red; exit 1 }
